# Generated by Django 4.1.4 on 2023-01-07 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvtoFull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('title_tr', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=1024, verbose_name='The address is')),
                ('price', models.IntegerField(verbose_name='Starting price')),
                ('upload', models.FileField(upload_to='')),
                ('category_en', models.CharField(blank=True, choices=[('Real estate', 'Real estate'), ('Auto', 'Auto'), ('Job', 'Job'), ('Services', 'Services'), ('For kids', 'For kids'), ('Electronics', 'Electronics'), ('House and garden', 'House and garden'), ('Fashion and style', 'Fashion and style')], default=None, max_length=255, null=True)),
                ('category_ru', models.CharField(blank=True, choices=[('Недвижимость', 'Недвижимость'), ('Авто', 'Авто'), ('Работа', 'Работа'), ('Услуги', 'Услуги'), ('Для детей', 'Для детей'), ('Электроника', 'Электроника'), ('Дом и сад', 'Дом и сад'), ('Мода и стиль', 'Мода и стиль')], default=None, max_length=255, null=True)),
                ('category_tr', models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True)),
                ('recommend', models.BooleanField()),
                ('publisher', models.BooleanField()),
                ('description', models.TextField()),
                ('sub_category_en', models.CharField(blank=True, choices=[('Cars', 'Cars'), ('Other technique', 'Other technique')], default=None, max_length=255, null=True)),
                ('sub_category_ru', models.CharField(blank=True, choices=[('Легковые автомобили', 'Легковые автомобили'), ('Другая техника', 'Другая техника')], default=None, max_length=255, null=True)),
                ('sub_category_tr', models.CharField(blank=True, choices=[('Arabalar', 'Arabalar'), ('Diğer teknik', 'Diğer teknik')], default=None, max_length=255, null=True)),
                ('brand', models.CharField(max_length=255)),
                ('mileage', models.IntegerField()),
                ('year', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChildrenFull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('title_tr', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=1024, verbose_name='The address is')),
                ('price', models.IntegerField(verbose_name='Starting price')),
                ('upload', models.FileField(upload_to='')),
                ('category_en', models.CharField(blank=True, choices=[('Real estate', 'Real estate'), ('Auto', 'Auto'), ('Job', 'Job'), ('Services', 'Services'), ('For kids', 'For kids'), ('Electronics', 'Electronics'), ('House and garden', 'House and garden'), ('Fashion and style', 'Fashion and style')], default=None, max_length=255, null=True)),
                ('category_ru', models.CharField(blank=True, choices=[('Недвижимость', 'Недвижимость'), ('Авто', 'Авто'), ('Работа', 'Работа'), ('Услуги', 'Услуги'), ('Для детей', 'Для детей'), ('Электроника', 'Электроника'), ('Дом и сад', 'Дом и сад'), ('Мода и стиль', 'Мода и стиль')], default=None, max_length=255, null=True)),
                ('category_tr', models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True)),
                ('recommend', models.BooleanField()),
                ('publisher', models.BooleanField()),
                ('description', models.TextField()),
                ('sub_category_en', models.CharField(choices=[("Children's clothing", "Children's clothing"), ("Children's shoes", "Children's shoes"), ('Baby strollers / Transport', 'Baby strollers / Transport'), ("Children's toys / Furniture", "Children's toys / Furniture"), ('Other goods for children', 'Other goods for children')], max_length=255)),
                ('sub_category_ru', models.CharField(choices=[('Детская одежда', 'детская одежда'), ('Детская обувь', 'детская обувь'), ('Детские коляски / Транспорт', 'детские коляски / Транспорт'), ('Детские игрушки / мебель', 'детские игрушки / Мебель'), ('Другие хорошие вещи для детей', 'Другие хорошие вещи для детей')], max_length=255)),
                ('sub_category_tr', models.CharField(choices=[('Çocuk giyim', 'çocuk giyim'), ('Çocuk ayakkabıları', 'çocuk ayakkabıları'), ('Bebek arabası / Taşıma', 'bebek arabası / Taşıma'), ('Çocuk oyuncakları / Mobilyaları', 'çocuk oyuncakları / Mobilyaları'), ('Çocuklar için diğer iyi şeyler', 'Çocuklar için diğer iyi şeyler')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name_en', models.CharField(max_length=255)),
                ('city_name_ru', models.CharField(max_length=255)),
                ('city_name_tr', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicsFull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('title_tr', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=1024, verbose_name='The address is')),
                ('price', models.IntegerField(verbose_name='Starting price')),
                ('upload', models.FileField(upload_to='')),
                ('category_en', models.CharField(blank=True, choices=[('Real estate', 'Real estate'), ('Auto', 'Auto'), ('Job', 'Job'), ('Services', 'Services'), ('For kids', 'For kids'), ('Electronics', 'Electronics'), ('House and garden', 'House and garden'), ('Fashion and style', 'Fashion and style')], default=None, max_length=255, null=True)),
                ('category_ru', models.CharField(blank=True, choices=[('Недвижимость', 'Недвижимость'), ('Авто', 'Авто'), ('Работа', 'Работа'), ('Услуги', 'Услуги'), ('Для детей', 'Для детей'), ('Электроника', 'Электроника'), ('Дом и сад', 'Дом и сад'), ('Мода и стиль', 'Мода и стиль')], default=None, max_length=255, null=True)),
                ('category_tr', models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True)),
                ('recommend', models.BooleanField()),
                ('publisher', models.BooleanField()),
                ('description', models.TextField()),
                ('sub_category_en', models.CharField(choices=[('Phones and accessories', 'Phones and accessories'), ('Computers / Tablets / Games', 'Computers / Tablets / Games'), ('TV / Photo / Video / Audio', 'TV / Photo / Video / Audio'), ('Other technique', 'Other technique')], max_length=255)),
                ('sub_category_ru', models.CharField(choices=[('Телефоны и аксессуары', 'Телефоны и аксессуары'), ('Компьютеры / планшеты / игры', 'Компьютеры / планшеты / игры'), ('ТВ / Фото / видео / Аудио', 'ТВ / Фото / видео / Аудио'), ('Другая техника', 'Другая техника')], max_length=255)),
                ('sub_category_tr', models.CharField(choices=[('Telefonlar ve aksesuarlar', 'Telefonlar ve aksesuarlar'), ('Bilgisayarlar / Tabletler / Oyunlar', 'Bilgisayarlar / Tabletler / Oyunlar'), ('TV / Fotoğraf / Video / Ses', 'TV / Fotoğraf / Video / Ses'), ('Diğer teknik', 'Diğer teknik')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FashionFull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('title_tr', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=1024, verbose_name='The address is')),
                ('price', models.IntegerField(verbose_name='Starting price')),
                ('upload', models.FileField(upload_to='')),
                ('category_en', models.CharField(blank=True, choices=[('Real estate', 'Real estate'), ('Auto', 'Auto'), ('Job', 'Job'), ('Services', 'Services'), ('For kids', 'For kids'), ('Electronics', 'Electronics'), ('House and garden', 'House and garden'), ('Fashion and style', 'Fashion and style')], default=None, max_length=255, null=True)),
                ('category_ru', models.CharField(blank=True, choices=[('Недвижимость', 'Недвижимость'), ('Авто', 'Авто'), ('Работа', 'Работа'), ('Услуги', 'Услуги'), ('Для детей', 'Для детей'), ('Электроника', 'Электроника'), ('Дом и сад', 'Дом и сад'), ('Мода и стиль', 'Мода и стиль')], default=None, max_length=255, null=True)),
                ('category_tr', models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True)),
                ('recommend', models.BooleanField()),
                ('publisher', models.BooleanField()),
                ('description', models.TextField()),
                ('sub_category_en', models.CharField(choices=[("Women's clothing", "Women's clothing"), ("Women's shoes", "Women's shoes"), ("Children's clothes", "Children's clothes"), ("Children's shoes", "Children's shoes"), ("Men's clothing", "Men's clothing"), ('Accessories', 'Accessories')], max_length=255)),
                ('sub_category_ru', models.CharField(choices=[('Женская одежда', 'женская одежда'), ('Женская обувь', 'женская обувь'), ('Детская одежда', 'детская одежда'), ('Детская обувь', 'детская обувь'), ('Мужская одежда', 'мужская одежда'), ('Аксессуары', 'Фурнитура')], max_length=255)),
                ('sub_category_tr', models.CharField(choices=[('Kadın giyim', 'kadın giyim'), ('Kadın ayakkabısı', 'kadın ayakkabısı'), ('Çocuk kıyafetleri', 'çocuk kıyafetleri'), ('Çocuk ayakkabıları', 'çocuk ayakkabıları'), ('Erkek giyim', 'erkek giyim'), ('Aksesuarlar', 'Aksesuarlar')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseGardenFull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('title_tr', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=1024, verbose_name='The address is')),
                ('price', models.IntegerField(verbose_name='Starting price')),
                ('upload', models.FileField(upload_to='')),
                ('category_en', models.CharField(blank=True, choices=[('Real estate', 'Real estate'), ('Auto', 'Auto'), ('Job', 'Job'), ('Services', 'Services'), ('For kids', 'For kids'), ('Electronics', 'Electronics'), ('House and garden', 'House and garden'), ('Fashion and style', 'Fashion and style')], default=None, max_length=255, null=True)),
                ('category_ru', models.CharField(blank=True, choices=[('Недвижимость', 'Недвижимость'), ('Авто', 'Авто'), ('Работа', 'Работа'), ('Услуги', 'Услуги'), ('Для детей', 'Для детей'), ('Электроника', 'Электроника'), ('Дом и сад', 'Дом и сад'), ('Мода и стиль', 'Мода и стиль')], default=None, max_length=255, null=True)),
                ('category_tr', models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True)),
                ('recommend', models.BooleanField()),
                ('publisher', models.BooleanField()),
                ('description', models.TextField()),
                ('sub_category_en', models.CharField(choices=[('Furniture', 'Furniture'), ('Food / Drinks', 'Food / Drinks'), ('Garden', 'Garden'), ('Interior items', 'Interior items'), ('Construction / Renovation', 'Construction / Renovation'), ('Other household goods', 'Other household goods')], max_length=255)),
                ('sub_category_ru', models.CharField(choices=[('Мебель', 'Furniture'), ('Еда / напитки', 'Еда / напитки'), ('Сад', 'Огород'), ('Предметы интерьера', 'Предметы интерьера'), ('Строительство / реконструкция', 'Строительство / реновация'), ('Прочие товары для дома', 'Прочие товары для дома')], max_length=255)),
                ('sub_category_tr', models.CharField(choices=[('Mobilya', 'Mobilya'), ('Yiyecek / içecekler', 'Yiyecek / içecekler'), ('Bahçe', 'Bahçe'), ('İç eşyalar', 'iç eşyalar'), ('İnşaat / Yenileme', 'İnşaat / Yenileme'), ('Diğer ev eşyaları', 'Diğer ev eşyaları')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_dollar', models.IntegerField()),
                ('monet_rub', models.IntegerField()),
                ('money_tr', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RealtyFull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('title_tr', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=1024, verbose_name='The address is')),
                ('price', models.IntegerField(verbose_name='Starting price')),
                ('upload', models.FileField(upload_to='')),
                ('category_en', models.CharField(blank=True, choices=[('Real estate', 'Real estate'), ('Auto', 'Auto'), ('Job', 'Job'), ('Services', 'Services'), ('For kids', 'For kids'), ('Electronics', 'Electronics'), ('House and garden', 'House and garden'), ('Fashion and style', 'Fashion and style')], default=None, max_length=255, null=True)),
                ('category_ru', models.CharField(blank=True, choices=[('Недвижимость', 'Недвижимость'), ('Авто', 'Авто'), ('Работа', 'Работа'), ('Услуги', 'Услуги'), ('Для детей', 'Для детей'), ('Электроника', 'Электроника'), ('Дом и сад', 'Дом и сад'), ('Мода и стиль', 'Мода и стиль')], default=None, max_length=255, null=True)),
                ('category_tr', models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True)),
                ('recommend', models.BooleanField()),
                ('publisher', models.BooleanField()),
                ('description', models.TextField()),
                ('sub_category_en', models.CharField(blank=True, choices=[('Apartments', 'Apartments'), ('House', 'House'), ('Land', 'Land'), ('Other', 'Other')], default=None, max_length=255, null=True)),
                ('sub_category_ru', models.CharField(blank=True, choices=[('Апартаменты', 'Апартаменты'), ('Дом', 'House'), ('Земля', 'Land'), ('Другое', 'Другое')], default=None, max_length=255, null=True)),
                ('sub_category_tr', models.CharField(blank=True, choices=[('Daireler', 'Daireler'), ('Ev', 'Ev'), ('Arazi', 'Arazi'), ('Diğer', 'Diğer')], default=None, max_length=255, null=True)),
                ('all_old_new_en', models.CharField(blank=True, choices=[('All', 'All'), ('Old', 'Old'), ('New', 'New')], default=None, max_length=255, null=True)),
                ('all_old_new_ru', models.CharField(blank=True, choices=[('Все', 'Все'), ('Старый', 'Старый'), ('Новый', 'Новый')], default=None, max_length=255, null=True)),
                ('all_old_new_tr', models.CharField(blank=True, choices=[('Tümü', 'Tümü'), ('Eski', 'Eski'), ('Yeni', 'Yeni')], default=None, max_length=255, null=True)),
                ('number_rooms_en', models.CharField(blank=True, choices=[('Studio', 'Studio'), ('1+1', '1+1'), ('2+1', '2+1'), ('3+1', '3+1'), ('4+1 and more', '4+1 and more')], default=None, max_length=255, null=True)),
                ('number_rooms_ru', models.CharField(blank=True, choices=[('Студия', 'Студия'), ('4+1 и более', '4+1 и более')], default=None, max_length=255, null=True)),
                ('number_rooms_tr', models.CharField(blank=True, choices=[('Stüdyo', 'Stüdyo'), ('4 + 1 ve daha fazlası', '4 + 1 ve daha fazlası')], default=None, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServicesFull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('title_tr', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=1024, verbose_name='The address is')),
                ('price', models.IntegerField(verbose_name='Starting price')),
                ('upload', models.FileField(upload_to='')),
                ('category_en', models.CharField(blank=True, choices=[('Real estate', 'Real estate'), ('Auto', 'Auto'), ('Job', 'Job'), ('Services', 'Services'), ('For kids', 'For kids'), ('Electronics', 'Electronics'), ('House and garden', 'House and garden'), ('Fashion and style', 'Fashion and style')], default=None, max_length=255, null=True)),
                ('category_ru', models.CharField(blank=True, choices=[('Недвижимость', 'Недвижимость'), ('Авто', 'Авто'), ('Работа', 'Работа'), ('Услуги', 'Услуги'), ('Для детей', 'Для детей'), ('Электроника', 'Электроника'), ('Дом и сад', 'Дом и сад'), ('Мода и стиль', 'Мода и стиль')], default=None, max_length=255, null=True)),
                ('category_tr', models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True)),
                ('recommend', models.BooleanField()),
                ('publisher', models.BooleanField()),
                ('description', models.TextField()),
                ('sub_category_en', models.CharField(choices=[('Cleaning', 'Cleaning'), ('Business', 'Business'), ('Domestic services', 'Domestic services'), ('Beauty / Health', 'Beauty / Health'), ('Education', 'Education'), ('Transport', 'Transport'), ('Construction / Repair', 'Construction / Repair'), ('Other', 'Other')], max_length=255)),
                ('sub_category_ru', models.CharField(choices=[('Уборка', 'Очищение'), ('Бизнес', 'Business'), ('Бытовые услуги', 'Бытовые услуги'), ('Красота / здоровье', 'Красота / Здоровье'), ('Образование', 'Education'), ('Транспорт', 'Транспортировка'), ('Строительство / ремонт', 'Строительство / ремонт'), ('Другое', 'Прочее')], max_length=255)),
                ('sub_category_tr', models.CharField(choices=[('Temizlik', 'Temizlik'), ('İş', 'iş'), ('Yurt içi hizmetler', 'Yurt içi hizmetler'), ('Güzellik / Sağlık', 'Güzellik / Sağlık'), ('Eğitim', 'Eğitim'), ('Ulaşım', 'Ulaşım'), ('İnşaat / Onarım', 'İnşaat / Onarım'), ('Diğer', 'Diğer')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDark', models.BooleanField()),
                ('img', models.FileField(upload_to='stock/')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_tr', models.CharField(max_length=255, null=True)),
                ('desc', models.TextField()),
                ('desc_ru', models.TextField(null=True)),
                ('desc_en', models.TextField(null=True)),
                ('desc_tr', models.TextField(null=True)),
                ('background', models.FileField(upload_to='stock/')),
            ],
        ),
        migrations.CreateModel(
            name='WorkFull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('title_tr', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=1024, verbose_name='The address is')),
                ('price', models.IntegerField(verbose_name='Starting price')),
                ('upload', models.FileField(upload_to='')),
                ('category_en', models.CharField(blank=True, choices=[('Real estate', 'Real estate'), ('Auto', 'Auto'), ('Job', 'Job'), ('Services', 'Services'), ('For kids', 'For kids'), ('Electronics', 'Electronics'), ('House and garden', 'House and garden'), ('Fashion and style', 'Fashion and style')], default=None, max_length=255, null=True)),
                ('category_ru', models.CharField(blank=True, choices=[('Недвижимость', 'Недвижимость'), ('Авто', 'Авто'), ('Работа', 'Работа'), ('Услуги', 'Услуги'), ('Для детей', 'Для детей'), ('Электроника', 'Электроника'), ('Дом и сад', 'Дом и сад'), ('Мода и стиль', 'Мода и стиль')], default=None, max_length=255, null=True)),
                ('category_tr', models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True)),
                ('recommend', models.BooleanField()),
                ('publisher', models.BooleanField()),
                ('description', models.TextField()),
                ('sub_category_en', models.CharField(choices=[('Retail / sales /purchasing', 'Retail / sales /purchasing'), ('Logistics / Warehouse / Delivery', 'Logistics / Warehouse / Delivery'), ('Construction / finishing works', 'Construction / finishing works'), ('Construction / finishing works', 'Construction / finishing works'), ('Administrative staff / HR / Secretariat', 'Administrative staff / HR / Secretariat'), ('Security / security', 'Security / security'), ('Cleaning / Home staff', 'Cleaning / Home staff')], max_length=255)),
                ('sub_category_ru', models.CharField(choices=[('Розничная торговля / продажи /закупки', 'Розничная торговля / продажи /закупки'), ('Логистика / Склад / Доставка', 'Логистика / Склад / Доставка'), ('Строительные / отделочные работы', 'Строительные / отделочные работы'), ('Строительные / отделочные работы', 'Строительные / отделочные работы'), ('Административный персонал / Отдел кадров / Секретариат', 'Административный персонал / отдел кадров / Секретариат'), ('Охрана / охранный', 'Охрана / охраняемость'), ('Уборка / Домашний персонал', 'Уборка / Домашний персонал')], max_length=255)),
                ('sub_category_tr', models.CharField(choices=[('Perakende / satış / satın alma', 'Perakende / satış / satın alma'), ('Lojistik / Depo / Teslimat', 'Lojistik / Depo / Teslimat'), ('İnşaat / bitirme işleri', 'İnşaat / bitirme işleri'), ('İnşaat / bitirme işleri', 'İnşaat / bitirme işleri'), ('İdari personel / İK / Sekreterlik', 'İdari personel / İK / Sekreterlik'), ('Güvenlik / güvenlik', 'Güvenlik / güvenlik'), ('Temizlik / Ev personeli', 'Temizlik / Ev personeli')], max_length=255)),
                ('for_work_type_en', models.CharField(choices=[('for work', 'for work'), ('for an employee', 'for an employee')], max_length=255)),
                ('for_work_type_ru', models.CharField(choices=[('для работы', 'для работы'), ('для сотрудника', 'для служащего')], max_length=255)),
                ('for_work_type_tr', models.CharField(choices=[('iş için', 'iş için'), ('bir çalışan için', 'bir çalışan için')], max_length=255)),
                ('employment_en', models.CharField(choices=[('Full time', 'Full time'), ('Partial', 'Partial'), ('Remote', 'Remote')], max_length=255)),
                ('employment_ru', models.CharField(choices=[('Полный рабочий день', 'Полный рабочий день'), ('Частичный', 'Частичный'), ('Удаленный', 'Remote')], max_length=255)),
                ('employment_tr', models.CharField(choices=[('Tam zamanlı', 'Tam zamanlı'), ('Kısmi', 'Kısmi'), ('Uzak', 'Uzak')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkFullViewsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('avto_full', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sections.workfull')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkFullUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploads', models.FileField(upload_to='')),
                ('work_full_upload', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sections.workfull')),
            ],
        ),
        migrations.CreateModel(
            name='WorkFullFavouritesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avto_full', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sections.workfull')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesFullViewsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('avto_full', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sections.servicesfull')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesFullUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploads', models.FileField(upload_to='')),
                ('services_full_upload', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sections.servicesfull')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesFullFavouritesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avto_full', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sections.servicesfull')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RealtyFullViewsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('avto_full', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sections.realtyfull')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RealtyFullUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploads', models.FileField(upload_to='')),
                ('realty_full_upload', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='realty_full_upload', to='sections.realtyfull')),
            ],
        ),
        migrations.CreateModel(
            name='RealtyFullFavouritesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avto_full', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sections.realtyfull')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HouseGardenFullViewsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('avto_full', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sections.housegardenfull')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HouseGardenFullUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploads', models.FileField(upload_to='')),
                ('house_garden_full_upload', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sections.housegardenfull')),
            ],
        ),
        migrations.CreateModel(
            name='HouseGardenFullFavouritesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avto_full', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sections.housegardenfull')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FashionFullViewsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('avto_full', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sections.fashionfull')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FashionFullUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploads', models.FileField(upload_to='')),
                ('fashion_full_upload', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sections.fashionfull')),
            ],
        ),
        migrations.CreateModel(
            name='FashionFullFavouritesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avto_full', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sections.fashionfull')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicsFullViewsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('avto_full', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sections.electronicsfull')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicsFullUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploads', models.FileField(upload_to='')),
                ('electronics_full_upload', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sections.electronicsfull')),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicsFullFavouritesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avto_full', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sections.electronicsfull')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChildrenFullViewsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('avto_full', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sections.childrenfull')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChildrenFullUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploads', models.FileField(upload_to='')),
                ('services_full_upload', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sections.childrenfull')),
            ],
        ),
        migrations.CreateModel(
            name='ChildrenFullFavouritesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avto_full', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sections.childrenfull')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvtoFullViewsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('avto_full', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sections.avtofull')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvtoFullUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploads', models.FileField(upload_to='')),
                ('avto_full_upload', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sections.avtofull')),
            ],
        ),
        migrations.CreateModel(
            name='AvtoFullFavouritesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avto_full', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sections.avtofull')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
