# Generated by Django 4.0 on 2022-12-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avtofull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='avtofull',
            name='sub_category_ru',
            field=models.CharField(choices=[('Arabalar', 'Arabalar'), ('Diğer teknik', 'Diğer teknik')], max_length=255),
        ),
        migrations.AlterField(
            model_name='childrenfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='childrenfull',
            name='sub_category_ru',
            field=models.CharField(choices=[('Детская одежда', 'детская одежда'), ('Детская обувь', 'детская обувь'), ('Детские коляски / Транспорт', 'детские коляски / Транспорт'), ('Детские игрушки / мебель', 'детские игрушки / Мебель'), ('Другие хорошие вещи для детей', 'Другие хорошие вещи для детей')], max_length=255),
        ),
        migrations.AlterField(
            model_name='childrenfull',
            name='sub_category_tr',
            field=models.CharField(choices=[('Çocuk giyim', 'çocuk giyim'), ('Çocuk ayakkabıları', 'çocuk ayakkabıları'), ('Bebek arabası / Taşıma', 'bebek arabası / Taşıma'), ('Çocuk oyuncakları / Mobilyaları', 'çocuk oyuncakları / Mobilyaları'), ('Çocuklar için diğer iyi şeyler', 'Çocuklar için diğer iyi şeyler')], max_length=255),
        ),
        migrations.AlterField(
            model_name='electronicsfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='electronicsfull',
            name='sub_category_ru',
            field=models.CharField(choices=[('Телефоны и аксессуары', 'Телефоны и аксессуары'), ('Компьютеры / планшеты / игры', 'Компьютеры / планшеты / игры'), ('ТВ / Фото / видео / Аудио', 'ТВ / Фото / видео / Аудио'), ('Другая техника', 'Другая техника')], max_length=255),
        ),
        migrations.AlterField(
            model_name='fashionfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fashionfull',
            name='sub_category_ru',
            field=models.CharField(choices=[('Женская одежда', 'женская одежда'), ('Женская обувь', 'женская обувь'), ('Детская одежда', 'детская одежда'), ('Детская обувь', 'детская обувь'), ('Мужская одежда', 'мужская одежда'), ('Аксессуары', 'Фурнитура')], max_length=255),
        ),
        migrations.AlterField(
            model_name='fashionfull',
            name='sub_category_tr',
            field=models.CharField(choices=[('Kadın giyim', 'kadın giyim'), ('Kadın ayakkabısı', 'kadın ayakkabısı'), ('Çocuk kıyafetleri', 'çocuk kıyafetleri'), ('Çocuk ayakkabıları', 'çocuk ayakkabıları'), ('Erkek giyim', 'erkek giyim'), ('Aksesuarlar', 'Aksesuarlar')], max_length=255),
        ),
        migrations.AlterField(
            model_name='housegardenfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='housegardenfull',
            name='sub_category_ru',
            field=models.CharField(choices=[('Мебель', 'Furniture'), ('Еда / напитки', 'Еда / напитки'), ('Сад', 'Огород'), ('Предметы интерьера', 'Предметы интерьера'), ('Строительство / реконструкция', 'Строительство / реновация'), ('Прочие товары для дома', 'Прочие товары для дома')], max_length=255),
        ),
        migrations.AlterField(
            model_name='housegardenfull',
            name='sub_category_tr',
            field=models.CharField(choices=[('Mobilya', 'Mobilya'), ('Yiyecek / içecekler', 'Yiyecek / içecekler'), ('Bahçe', 'Bahçe'), ('İç eşyalar', 'iç eşyalar'), ('İnşaat / Yenileme', 'İnşaat / Yenileme'), ('Diğer ev eşyaları', 'Diğer ev eşyaları')], max_length=255),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='all_old_new_tr',
            field=models.CharField(choices=[('Tümü', 'Tümü'), ('Eski', 'Eski'), ('Yeni', 'Yeni')], max_length=255),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='number_rooms_ru',
            field=models.CharField(choices=[('Студия', 'Студия'), ('4+1 и более', '4+1 и более')], max_length=255),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='number_rooms_tr',
            field=models.CharField(choices=[('Stüdyo', 'Stüdyo'), ('4 + 1 ve daha fazlası', '4 + 1 ve daha fazlası')], max_length=255),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='sell_type_ru',
            field=models.CharField(choices=[('Арендовать', 'Арендовать'), ('Купить', 'Купить')], max_length=255),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='sell_type_tr',
            field=models.CharField(choices=[('Kira', 'Kira'), ('Satın Al', 'Satın Al')], max_length=255),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='sub_category_ru',
            field=models.CharField(choices=[('Апартаменты', 'Апартаменты'), ('Дом', 'House'), ('Земля', 'Land'), ('Другое', 'Другое')], max_length=255, verbose_name='Sub Apartment'),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='sub_category_tr',
            field=models.CharField(choices=[('Daireler', 'Daireler'), ('Ev', 'Ev'), ('Arazi', 'Arazi'), ('Diğer', 'Diğer')], max_length=255, verbose_name='Sub Apartment'),
        ),
        migrations.AlterField(
            model_name='servicesfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesfull',
            name='sub_category_ru',
            field=models.CharField(choices=[('Уборка', 'Очищение'), ('Бизнес', 'Business'), ('Бытовые услуги', 'Бытовые услуги'), ('Красота / здоровье', 'Красота / Здоровье'), ('Образование', 'Education'), ('Транспорт', 'Транспортировка'), ('Строительство / ремонт', 'Строительство / ремонт'), ('Другое', 'Прочее')], max_length=255),
        ),
        migrations.AlterField(
            model_name='servicesfull',
            name='sub_category_tr',
            field=models.CharField(choices=[('Temizlik', 'Temizlik'), ('İş', 'iş'), ('Yurt içi hizmetler', 'Yurt içi hizmetler'), ('Güzellik / Sağlık', 'Güzellik / Sağlık'), ('Eğitim', 'Eğitim'), ('Ulaşım', 'Ulaşım'), ('İnşaat / Onarım', 'İnşaat / Onarım'), ('Diğer', 'Diğer')], max_length=255),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='employment_ru',
            field=models.CharField(choices=[('Полный рабочий день', 'Полный рабочий день'), ('Частичный', 'Частичный'), ('Удаленный', 'Remote')], max_length=255),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='for_work_type_ru',
            field=models.CharField(choices=[('для работы', 'для работы'), ('для сотрудника', 'для служащего')], max_length=255),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='sub_category_ru',
            field=models.CharField(choices=[('Розничная торговля / продажи /закупки', 'Розничная торговля / продажи /закупки'), ('Логистика / Склад / Доставка', 'Логистика / Склад / Доставка'), ('Строительные / отделочные работы', 'Строительные / отделочные работы'), ('Строительные / отделочные работы', 'Строительные / отделочные работы'), ('Административный персонал / Отдел кадров / Секретариат', 'Административный персонал / отдел кадров / Секретариат'), ('Охрана / охранный', 'Охрана / охраняемость'), ('Уборка / Домашний персонал', 'Уборка / Домашний персонал')], max_length=255),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='sub_category_tr',
            field=models.CharField(choices=[('Perakende / satış / satın alma', 'Perakende / satış / satın alma'), ('Lojistik / Depo / Teslimat', 'Lojistik / Depo / Teslimat'), ('İnşaat / bitirme işleri', 'İnşaat / bitirme işleri'), ('İnşaat / bitirme işleri', 'İnşaat / bitirme işleri'), ('İdari personel / İK / Sekreterlik', 'İdari personel / İK / Sekreterlik'), ('Güvenlik / güvenlik', 'Güvenlik / güvenlik'), ('Temizlik / Ev personeli', 'Temizlik / Ev personeli')], max_length=255),
        ),
    ]
