# Generated by Django 4.0 on 2022-12-11 13:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvtoFull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Product name')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=1024, verbose_name='The address is')),
                ('price', models.IntegerField(verbose_name='Starting price')),
                ('upload', models.FileField(upload_to='')),
                ('category_en', models.CharField(blank=True, choices=[('Real estate', 'Real estate'), ('Auto', 'Auto'), ('Job', 'Job'), ('Services', 'Services'), ('For kids', 'For kids'), ('Electronics', 'Electronics'), ('House and garden', 'House and garden'), ('Fashion and style', 'Fashion and style')], default=None, max_length=255, null=True)),
                ('category_ru', models.CharField(blank=True, choices=[('Недвижимость', 'Недвижимость'), ('Авто', 'Авто'), ('Работа', 'Работа'), ('Услуги', 'Услуги'), ('Для детей', 'Для детей'), ('Электроника', 'Электроника'), ('Дом и сад', 'Дом и сад'), ('Мода и стиль', 'Мода и стиль')], default=None, max_length=255, null=True)),
                ('category_tr', models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True)),
                ('recommend', models.BooleanField()),
                ('sub_apartment_en', models.CharField(choices=[('Cars', 'Cars'), ('Other technique', 'Other technique')], max_length=255)),
                ('sub_apartment_ru', models.CharField(choices=[('Машины', 'Машины'), ('Другая техника', 'Другая техника')], max_length=255)),
                ('sub_apartment_tr', models.CharField(choices=[('Arabalar', 'Arabalar'), ('Diğer teknik', 'Diğer teknik')], max_length=255)),
                ('brand_en', models.CharField(max_length=255)),
                ('mileage', models.IntegerField()),
                ('year', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser', verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name_en',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name_ru',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name_tr',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='AvtoFullUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploads', models.FileField(upload_to='')),
                ('avto_full_upload', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sections.avtofull')),
            ],
        ),
    ]
