# Generated by Django 4.1.4 on 2023-01-08 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childrenfullupload',
            old_name='services_full_upload',
            new_name='children_full_upload',
        ),
    ]
