# Generated by Django 4.0 on 2022-12-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avtofull',
            name='sub_category_ru',
            field=models.CharField(choices=[('Легковые автомобили', 'Легковые автомобили'), ('Другая техника', 'Другая техника')], max_length=255),
        ),
        migrations.AlterField(
            model_name='fashionfull',
            name='sub_category_ru',
            field=models.CharField(choices=[('Женская одежда', 'Женская одежда'), ('ботинки женские', 'ботинки женские'), ('Детская одежда', 'Детская одежда'), ('Детские туфли', 'Детские туфли'), ('Мужская одежда', 'Мужская одежда'), ('Аксессуары', 'Аксессуары')], max_length=255),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='sell_type_ru',
            field=models.CharField(choices=[('Арендная плата', 'Арендная плата'), ('Купить', 'Купить')], max_length=255),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='sub_category_tr',
            field=models.CharField(choices=[('Daireler', 'Daireler'), ('Ev', 'Ev'), ('Kara', 'Kara'), ('Diğer', 'Diğer')], max_length=255, verbose_name='Sub Apartment'),
        ),
        migrations.AlterField(
            model_name='servicesfull',
            name='sub_category_tr',
            field=models.CharField(choices=[('Temizlik', 'Temizlik'), ('İşletme', 'İşletme'), ('Yerli hizmetler', 'Yerli hizmetler'), ('Güzellik', 'Güzellik'), ('Eğitim', 'Eğitim'), ('Ulaşım', 'Ulaşım'), ('İnşaat / Onarım', 'İnşaat / Onarım'), ('Diğer', 'Diğer')], max_length=255),
        ),
    ]
