# Generated by Django 4.0 on 2022-12-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_avtofull_alter_city_city_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avtofull',
            name='brand_en_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='avtofull',
            name='brand_en_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='avtofull',
            name='brand_en_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='avtofull',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='avtofull',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='avtofull',
            name='title_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Product name'),
        ),
    ]
