# Generated by Django 4.0 on 2022-12-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_alter_avtofull_sub_category_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avtofull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('ev ve bahçe', 'ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='childrenfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('ev ve bahçe', 'ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='childrenfull',
            name='sub_category_ru',
            field=models.CharField(choices=[('Детская одежда', 'Детская одежда'), ('Детские туфли', 'Детские туфли'), ('Детские коляски / Транспорт', 'Детские коляски / Транспорт'), ('Детские игрушки / Мебель', 'Детские игрушки / Мебель'), ('Другие товары для детей', 'Другие товары для детей')], max_length=255),
        ),
        migrations.AlterField(
            model_name='childrenfull',
            name='sub_category_tr',
            field=models.CharField(choices=[('Çocuk giyim', 'Çocuk giyim'), ('çocuk ayakkabıları', 'çocuk ayakkabıları'), ('Bebek arabaları / Taşıma', 'Bebek arabaları / Taşıma'), ('Çocuk oyuncakları / Mobilya', 'Çocuk oyuncakları / Mobilya'), ('Çocuklar için diğer ürünler', 'Çocuklar için diğer ürünler')], max_length=255),
        ),
        migrations.AlterField(
            model_name='electronicsfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('ev ve bahçe', 'ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='electronicsfull',
            name='sub_category_ru',
            field=models.CharField(choices=[('Телефоны и аксессуары', 'Телефоны и аксессуары'), ('Компьютеры / Планшеты / Игры', 'Компьютеры / Планшеты / Игры'), ('ТВ/Фото/Видео/Аудио', 'ТВ/Фото/Видео/Аудио'), ('Другая техника', 'Другая техника')], max_length=255),
        ),
        migrations.AlterField(
            model_name='electronicsfull',
            name='sub_category_tr',
            field=models.CharField(choices=[('Telefonlar ve aksesuarlar', 'Telefonlar ve aksesuarlar'), ('Bilgisayarlar / Tabletler / Oyunlar', 'Bilgisayarlar / Tabletler / Oyunlar'), ('TV / Fotoğraf / Video / Ses', 'TV / Fotoğraf / Video / Ses'), ('Diğer teknik', 'Diğer teknik')], max_length=255),
        ),
        migrations.AlterField(
            model_name='fashionfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('ev ve bahçe', 'ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fashionfull',
            name='sub_category_tr',
            field=models.CharField(choices=[('Bayan giyimi', 'Bayan giyimi'), ('Kadın ayakkabıları', 'Kadın ayakkabıları'), ('Çocuk giysileri', 'Çocuk giysileri'), ('çocuk ayakkabıları', 'çocuk ayakkabıları'), ('Erkek giyim', 'Erkek giyim'), ('Aksesuarlar', 'Aksesuarlar')], max_length=255),
        ),
        migrations.AlterField(
            model_name='housegardenfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('ev ve bahçe', 'ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='housegardenfull',
            name='sub_category_ru',
            field=models.CharField(choices=[('Мебель', 'Мебель'), ('Еда напитки', 'Еда напитки'), ('Сад', 'Сад'), ('Предметы интерьера', 'Предметы интерьера'), ('Строительство/Ремонт', 'Строительство/Ремонт'), ('Другие товары для дома', 'Другие товары для дома')], max_length=255),
        ),
        migrations.AlterField(
            model_name='housegardenfull',
            name='sub_category_tr',
            field=models.CharField(choices=[('Mobilya', 'Mobilya'), ('Yiyecek / İçecek', 'Yiyecek / İçecek'), ('Bahçe', 'Bahçe'), ('İç öğeler', 'İç öğeler'), ('İnşaat / Tadilat', 'İnşaat / Tadilat'), ('Diğer ev eşyaları', 'Diğer ev eşyaları')], max_length=255),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('ev ve bahçe', 'ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='number_rooms_ru',
            field=models.CharField(choices=[('Студия', 'Студия'), ('1+1', '1+1'), ('2+1', '2+1'), ('3+1', '3+1'), ('4+1 и более', '4+1 и более')], max_length=255),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='number_rooms_tr',
            field=models.CharField(choices=[('Stüdyo', 'Stüdyo'), ('1+1', '1+1'), ('2+1', '2+1'), ('3+1', '3+1'), ('4+1 ve üzeri', '4+1 ve üzeri')], max_length=255),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='sub_category_ru',
            field=models.CharField(choices=[('Апартаменты', 'Апартаменты'), ('Дом', 'Дом'), ('Земельные участки', 'Земельные участки'), ('Другой', 'Другой')], max_length=255, verbose_name='Sub Apartment'),
        ),
        migrations.AlterField(
            model_name='servicesfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('ev ve bahçe', 'ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesfull',
            name='sub_category_ru',
            field=models.CharField(choices=[('Уборка', 'Уборка'), ('Бизнес', 'Бизнес'), ('Бытовые услуги', 'Бытовые услуги'), ('Красота и Здоровье', 'Красота и Здоровье'), ('Образование', 'Образование'), ('Транспорт', 'Транспорт'), ('Строительство/Ремонт', 'Строительство/Ремонт'), ('Другой', 'Другой')], max_length=255),
        ),
        migrations.AlterField(
            model_name='servicesfull',
            name='sub_category_tr',
            field=models.CharField(choices=[('Temizlik', 'Temizlik'), ('İşletme', 'İşletme'), ('Ev hizmetleri', 'Ev hizmetleri'), ('Güzellik', 'Güzellik'), ('Eğitim', 'Eğitim'), ('Ulaşım', 'Ulaşım'), ('İnşaat / Onarım', 'İnşaat / Onarım'), ('Diğer', 'Diğer')], max_length=255),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('ev ve bahçe', 'ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='for_work_type_ru',
            field=models.CharField(choices=[('для работы', 'для работы'), ('для сотрудника', 'для сотрудника')], max_length=255),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='for_work_type_tr',
            field=models.CharField(choices=[('iş için', 'iş için'), ('bir çalışan için', 'bir çalışan için')], max_length=255),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='sub_category_ru',
            field=models.CharField(choices=[('Розничная торговля / продажи / закупки', 'Розничная торговля / продажи / закупки'), ('Логистика / Склад / Доставка', 'Логистика / Склад / Доставка'), ('Строительные/отделочные работы', 'Строительные/отделочные работы'), ('Строительные/отделочные работы', 'Строительные/отделочные работы'), ('Административный персонал/HR/Секретариат', 'Административный персонал/HR/Секретариат'), ('Безопасность / безопасность', 'Безопасность / безопасность'), ('Уборка / Домашний персонал', 'Уборка / Домашний персонал')], max_length=255),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='sub_category_tr',
            field=models.CharField(choices=[('Perakende / satış / satın alma', 'Perakende / satış / satın alma'), ('Lojistik / Depo / Teslimat', 'Lojistik / Depo / Teslimat'), ('İnşaat / bitirme işleri', 'İnşaat / bitirme işleri'), ('İnşaat / bitirme işleri', 'İnşaat / bitirme işleri'), ('İdari personel / İK / Sekreterlik', 'İdari personel / İK / Sekreterlik'), ('güvenlik / güvenlik', 'güvenlik / güvenlik'), ('Temizlik / Ev personeli', 'Temizlik / Ev personeli')], max_length=255),
        ),
    ]
