# Generated by Django 4.1.4 on 2023-01-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_avtofull_city_avtofull_geocode_childrenfull_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avtofull',
            name='currency',
            field=models.CharField(blank=True, choices=[('₽', '₽'), ('$', '$'), ('₤', '₤')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='childrenfull',
            name='currency',
            field=models.CharField(blank=True, choices=[('₽', '₽'), ('$', '$'), ('₤', '₤')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='electronicsfull',
            name='currency',
            field=models.CharField(blank=True, choices=[('₽', '₽'), ('$', '$'), ('₤', '₤')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='fashionfull',
            name='currency',
            field=models.CharField(blank=True, choices=[('₽', '₽'), ('$', '$'), ('₤', '₤')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='housegardenfull',
            name='currency',
            field=models.CharField(blank=True, choices=[('₽', '₽'), ('$', '$'), ('₤', '₤')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='realtyfull',
            name='currency',
            field=models.CharField(blank=True, choices=[('₽', '₽'), ('$', '$'), ('₤', '₤')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='servicesfull',
            name='currency',
            field=models.CharField(blank=True, choices=[('₽', '₽'), ('$', '$'), ('₤', '₤')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='workfull',
            name='currency',
            field=models.CharField(blank=True, choices=[('₽', '₽'), ('$', '$'), ('₤', '₤')], max_length=1, null=True),
        ),
    ]
