# Generated by Django 4.1.4 on 2023-01-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_alter_avtofull_title_en_alter_avtofull_title_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avtofull',
            name='sub_category_ru',
            field=models.CharField(blank=True, choices=[('Легковые автомобили', 'Легковые автомобили'), ('Другая техника', 'Другая техника')], default=None, max_length=255, null=True),
        ),
    ]
