# Generated by Django 4.0 on 2022-12-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_alter_avtofull_category_tr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avtofull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='childrenfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='childrenfull',
            name='sub_category_ru',
            field=models.CharField(choices=[('Детская одежда', 'Детская одежда'), ('Детские туфли', 'Детские туфли'), ('Детские коляски / транспорт', 'Детские коляски / транспорт'), ('Детские игрушки / мебель', 'Детские игрушки / мебель'), ('Другие товары для детей', 'Другие товары для детей')], max_length=255),
        ),
        migrations.AlterField(
            model_name='childrenfull',
            name='sub_category_tr',
            field=models.CharField(choices=[('Çocuk giyim', 'Çocuk giyim'), ('Çocuk ayakkabıları', 'Çocuk ayakkabıları'), ('Bebek arabası / ulaşım', 'Bebek arabası / ulaşım'), ('Çocuk oyuncakları / mobilyaları', 'Çocuk oyuncakları / mobilyaları'), ('Çocuklar için diğer mallar', 'Çocuklar için diğer mallar')], max_length=255),
        ),
        migrations.AlterField(
            model_name='electronicsfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='electronicsfull',
            name='sub_category_ru',
            field=models.CharField(choices=[('Телефоны и аксессуары', 'Телефоны и аксессуары'), ('Компьютеры / планшеты / игры', 'Компьютеры / планшеты / игры'), ('ТВ / фото / видео / аудио', 'ТВ / фото / видео / аудио'), ('Другая техника', 'Другая техника')], max_length=255),
        ),
        migrations.AlterField(
            model_name='electronicsfull',
            name='sub_category_tr',
            field=models.CharField(choices=[('Telefonlar ve Aksesuarlar', 'Telefonlar ve Aksesuarlar'), ('Bilgisayarlar / Tabletler / Oyunlar', 'Bilgisayarlar / Tabletler / Oyunlar'), ('TV / fotoğraf / video / ses', 'TV / fotoğraf / video / ses'), ('Diğer teknik', 'Diğer teknik')], max_length=255),
        ),
        migrations.AlterField(
            model_name='fashionfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fashionfull',
            name='sub_category_tr',
            field=models.CharField(choices=[('Bayan giyimi', 'Bayan giyimi'), ('Kadın Ayakkabıları', 'Kadın Ayakkabıları'), ('Çocuk giysileri', 'Çocuk giysileri'), ('Çocuk ayakkabıları', 'Çocuk ayakkabıları'), ('Erkek giyim', 'Erkek giyim'), ('Aksesuarlar', 'Aksesuarlar')], max_length=255),
        ),
        migrations.AlterField(
            model_name='housegardenfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='housegardenfull',
            name='sub_category_ru',
            field=models.CharField(choices=[('Мебель', 'Мебель'), ('Еда напитки', 'Еда напитки'), ('Сад', 'Сад'), ('Интерьер', 'Интерьер'), ('Строительство / ремонт', 'Строительство / ремонт'), ('Другие товары для дома', 'Другие товары для дома')], max_length=255),
        ),
        migrations.AlterField(
            model_name='housegardenfull',
            name='sub_category_tr',
            field=models.CharField(choices=[('Mobilya', 'Mobilya'), ('Yemek / İçecekler', 'Yemek / İçecekler'), ('Bahçe', 'Bahçe'), ('İç eşyalar', 'İç eşyalar'), ('İnşaat / Yenileme', 'İnşaat / Yenileme'), ('Diğer ev eşyaları', 'Diğer ev eşyaları')], max_length=255),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='number_rooms_ru',
            field=models.CharField(choices=[('Студия', 'Студия'), ('1+1', '1+1'), ('2+1', '2+1'), ('3+1', '3+1'), ('4+1 и больше', '4+1 и больше')], max_length=255),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='number_rooms_tr',
            field=models.CharField(choices=[('Stüdyo', 'Stüdyo'), ('1+1', '1+1'), ('2+1', '2+1'), ('3+1', '3+1'), ('4+1 ve daha fazlası', '4+1 ve daha fazlası')], max_length=255),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='sub_category_ru',
            field=models.CharField(choices=[('Квартиры', 'Квартиры'), ('Дом', 'Дом'), ('Земельные участки', 'Земельные участки'), ('Другой', 'Другой')], max_length=255, verbose_name='Sub Apartment'),
        ),
        migrations.AlterField(
            model_name='servicesfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesfull',
            name='sub_category_ru',
            field=models.CharField(choices=[('Уборка', 'Уборка'), ('Бизнес', 'Бизнес'), ('Внутренние услуги', 'Внутренние услуги'), ('Красота и Здоровье', 'Красота и Здоровье'), ('Образование', 'Образование'), ('Транспорт', 'Транспорт'), ('Строительство / ремонт', 'Строительство / ремонт'), ('Другой', 'Другой')], max_length=255),
        ),
        migrations.AlterField(
            model_name='servicesfull',
            name='sub_category_tr',
            field=models.CharField(choices=[('Temizlik', 'Temizlik'), ('İşletme', 'İşletme'), ('Yerli hizmetler', 'Yerli hizmetler'), ('Güzellik', 'Güzellik'), ('Eğitim', 'Eğitim'), ('Ulaşım', 'Ulaşım'), ('İnşaat / Onarım', 'İnşaat / Onarım'), ('Diğer', 'Diğer')], max_length=255),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='for_work_type_ru',
            field=models.CharField(choices=[('для работы', 'для работы'), ('для работника', 'для работника')], max_length=255),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='for_work_type_tr',
            field=models.CharField(choices=[('iş için', 'iş için'), ('Bir çalışan için', 'Bir çalışan için')], max_length=255),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='sub_category_ru',
            field=models.CharField(choices=[('Розничная торговля / продажи / покупка', 'Розничная торговля / продажи / покупка'), ('Логистика / склад / доставка', 'Логистика / склад / доставка'), ('Строительные / отдельные работы', 'Строительные / отдельные работы'), ('Строительные / отдельные работы', 'Строительные / отдельные работы'), ('Административный персонал / ЧСС / Секретариат', 'Административный персонал / ЧСС / Секретариат'), ('Безопасность / безопасность', 'Безопасность / безопасность'), ('Уборка / домашний персонал', 'Уборка / домашний персонал')], max_length=255),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='sub_category_tr',
            field=models.CharField(choices=[('Perakende / Satış / Satın Alma', 'Perakende / Satış / Satın Alma'), ('Lojistik / depo / teslimat', 'Lojistik / depo / teslimat'), ('İnşaat / Son İşler', 'İnşaat / Son İşler'), ('İnşaat / Son İşler', 'İnşaat / Son İşler'), ('İdari Personel / İK / Sekreterlik', 'İdari Personel / İK / Sekreterlik'), ('Güvenlik / Güvenlik', 'Güvenlik / Güvenlik'), ('Temizlik / Ev Personeli', 'Temizlik / Ev Personeli')], max_length=255),
        ),
    ]
