# Generated by Django 4.0 on 2022-12-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_avtofull_brand_en_en_avtofull_brand_en_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avtofull',
            old_name='brand_en_en',
            new_name='brand_ru',
        ),
        migrations.RenameField(
            model_name='avtofull',
            old_name='brand_en_ru',
            new_name='brand_tr',
        ),
        migrations.RemoveField(
            model_name='avtofull',
            name='brand_en_tr',
        ),
        migrations.AddField(
            model_name='avtofull',
            name='brand',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avtofull',
            name='brand_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
