# Generated by Django 4.0 on 2022-12-11 15:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sections', '0004_rename_brand_en_en_avtofull_brand_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Product name')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=1024, verbose_name='The address is')),
                ('price', models.IntegerField(verbose_name='Starting price')),
                ('upload', models.FileField(upload_to='')),
                ('category_en', models.CharField(blank=True, choices=[('Real estate', 'Real estate'), ('Auto', 'Auto'), ('Job', 'Job'), ('Services', 'Services'), ('For kids', 'For kids'), ('Electronics', 'Electronics'), ('House and garden', 'House and garden'), ('Fashion and style', 'Fashion and style')], default=None, max_length=255, null=True)),
                ('category_ru', models.CharField(blank=True, choices=[('Недвижимость', 'Недвижимость'), ('Авто', 'Авто'), ('Работа', 'Работа'), ('Услуги', 'Услуги'), ('Для детей', 'Для детей'), ('Электроника', 'Электроника'), ('Дом и сад', 'Дом и сад'), ('Мода и стиль', 'Мода и стиль')], default=None, max_length=255, null=True)),
                ('category_tr', models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True)),
                ('recommend', models.BooleanField()),
                ('sub_apartment_en', models.CharField(choices=[('Retail / sales /purchasing', 'Retail / sales /purchasing'), ('Logistics / Warehouse / Delivery', 'Logistics / Warehouse / Delivery'), ('Construction / finishing works', 'Construction / finishing works'), ('Construction / finishing works', 'Construction / finishing works'), ('Administrative staff / HR / Secretariat', 'Administrative staff / HR / Secretariat'), ('Security / security', 'Security / security'), ('Cleaning / Home staff', 'Cleaning / Home staff')], max_length=255)),
                ('sub_apartment_ru', models.CharField(choices=[('Розничная торговля / продажи / покупка', 'Розничная торговля / продажи / покупка'), ('Логистика / склад / доставка', 'Логистика / склад / доставка'), ('Строительные / отдельные работы', 'Строительные / отдельные работы'), ('Строительные / отдельные работы', 'Строительные / отдельные работы'), ('Административный персонал / ЧСС / Секретариат', 'Административный персонал / ЧСС / Секретариат'), ('Безопасность / безопасность', 'Безопасность / безопасность'), ('Уборка / домашний персонал', 'Уборка / домашний персонал')], max_length=255)),
                ('sub_apartment_tr', models.CharField(choices=[('Perakende / Satış / Satın Alma', 'Perakende / Satış / Satın Alma'), ('Lojistik / depo / teslimat', 'Lojistik / depo / teslimat'), ('İnşaat / Son İşler', 'İnşaat / Son İşler'), ('İnşaat / Son İşler', 'İnşaat / Son İşler'), ('İdari Personel / İK / Sekreterlik', 'İdari Personel / İK / Sekreterlik'), ('Güvenlik / Güvenlik', 'Güvenlik / Güvenlik'), ('Temizlik / Ev Personeli', 'Temizlik / Ev Personeli')], max_length=255)),
                ('for_work_type_en', models.CharField(choices=[('for work', 'for work'), ('for an employee', 'for an employee')], max_length=255)),
                ('for_work_type_ru', models.CharField(choices=[('Розничная торговля / продажи / покупка', 'Розничная торговля / продажи / покупка'), ('Логистика / склад / доставка', 'Логистика / склад / доставка'), ('Строительные / отдельные работы', 'Строительные / отдельные работы'), ('Строительные / отдельные работы', 'Строительные / отдельные работы'), ('Административный персонал / ЧСС / Секретариат', 'Административный персонал / ЧСС / Секретариат'), ('Безопасность / безопасность', 'Безопасность / безопасность'), ('Уборка / домашний персонал', 'Уборка / домашний персонал')], max_length=255)),
                ('for_work_type_tr', models.CharField(choices=[('Perakende / Satış / Satın Alma', 'Perakende / Satış / Satın Alma'), ('Lojistik / depo / teslimat', 'Lojistik / depo / teslimat'), ('İnşaat / Son İşler', 'İnşaat / Son İşler'), ('İnşaat / Son İşler', 'İnşaat / Son İşler'), ('İdari Personel / İK / Sekreterlik', 'İdari Personel / İK / Sekreterlik'), ('Güvenlik / Güvenlik', 'Güvenlik / Güvenlik'), ('Temizlik / Ev Personeli', 'Temizlik / Ev Personeli')], max_length=255)),
                ('employment_en', models.CharField(choices=[('Full time', 'Full time'), ('Partial', 'Partial'), ('Remote', 'Remote')], max_length=255)),
                ('employment_ru', models.CharField(choices=[('Розничная торговля / продажи / покупка', 'Розничная торговля / продажи / покупка'), ('Логистика / склад / доставка', 'Логистика / склад / доставка'), ('Строительные / отдельные работы', 'Строительные / отдельные работы'), ('Строительные / отдельные работы', 'Строительные / отдельные работы'), ('Административный персонал / ЧСС / Секретариат', 'Административный персонал / ЧСС / Секретариат'), ('Безопасность / безопасность', 'Безопасность / безопасность'), ('Уборка / домашний персонал', 'Уборка / домашний персонал')], max_length=255)),
                ('employment_tr', models.CharField(choices=[('Perakende / Satış / Satın Alma', 'Perakende / Satış / Satın Alma'), ('Lojistik / depo / teslimat', 'Lojistik / depo / teslimat'), ('İnşaat / Son İşler', 'İnşaat / Son İşler'), ('İnşaat / Son İşler', 'İnşaat / Son İşler'), ('İdari Personel / İK / Sekreterlik', 'İdari Personel / İK / Sekreterlik'), ('Güvenlik / Güvenlik', 'Güvenlik / Güvenlik'), ('Temizlik / Ev Personeli', 'Temizlik / Ev Personeli')], max_length=255)),
                ('salary', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser', verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkFullUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploads', models.FileField(upload_to='')),
                ('work_full_upload', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sections.workfull')),
            ],
        ),
    ]
