# Generated by Django 4.1.4 on 2023-03-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0005_alter_avtofull_category_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avtofull',
            name='full_price',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='childrenfull',
            name='full_price',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='electronicsfull',
            name='full_price',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='fashionfull',
            name='full_price',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='freefull',
            name='full_price',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='housegardenfull',
            name='full_price',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='realtyfull',
            name='full_price',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='servicesfull',
            name='full_price',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='workfull',
            name='full_price',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
