# Generated by Django 4.1.4 on 2023-03-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0006_avtofull_full_price_childrenfull_full_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avtofull',
            name='price_dol',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dollar price'),
        ),
        migrations.AddField(
            model_name='avtofull',
            name='price_eur',
            field=models.IntegerField(blank=True, null=True, verbose_name='Euro price'),
        ),
        migrations.AddField(
            model_name='avtofull',
            name='price_lir',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lira price'),
        ),
        migrations.AddField(
            model_name='childrenfull',
            name='price_dol',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dollar price'),
        ),
        migrations.AddField(
            model_name='childrenfull',
            name='price_eur',
            field=models.IntegerField(blank=True, null=True, verbose_name='Euro price'),
        ),
        migrations.AddField(
            model_name='childrenfull',
            name='price_lir',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lira price'),
        ),
        migrations.AddField(
            model_name='electronicsfull',
            name='price_dol',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dollar price'),
        ),
        migrations.AddField(
            model_name='electronicsfull',
            name='price_eur',
            field=models.IntegerField(blank=True, null=True, verbose_name='Euro price'),
        ),
        migrations.AddField(
            model_name='electronicsfull',
            name='price_lir',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lira price'),
        ),
        migrations.AddField(
            model_name='fashionfull',
            name='price_dol',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dollar price'),
        ),
        migrations.AddField(
            model_name='fashionfull',
            name='price_eur',
            field=models.IntegerField(blank=True, null=True, verbose_name='Euro price'),
        ),
        migrations.AddField(
            model_name='fashionfull',
            name='price_lir',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lira price'),
        ),
        migrations.AddField(
            model_name='freefull',
            name='price_dol',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dollar price'),
        ),
        migrations.AddField(
            model_name='freefull',
            name='price_eur',
            field=models.IntegerField(blank=True, null=True, verbose_name='Euro price'),
        ),
        migrations.AddField(
            model_name='freefull',
            name='price_lir',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lira price'),
        ),
        migrations.AddField(
            model_name='housegardenfull',
            name='price_dol',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dollar price'),
        ),
        migrations.AddField(
            model_name='housegardenfull',
            name='price_eur',
            field=models.IntegerField(blank=True, null=True, verbose_name='Euro price'),
        ),
        migrations.AddField(
            model_name='housegardenfull',
            name='price_lir',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lira price'),
        ),
        migrations.AddField(
            model_name='realtyfull',
            name='price_dol',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dollar price'),
        ),
        migrations.AddField(
            model_name='realtyfull',
            name='price_eur',
            field=models.IntegerField(blank=True, null=True, verbose_name='Euro price'),
        ),
        migrations.AddField(
            model_name='realtyfull',
            name='price_lir',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lira price'),
        ),
        migrations.AddField(
            model_name='servicesfull',
            name='price_dol',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dollar price'),
        ),
        migrations.AddField(
            model_name='servicesfull',
            name='price_eur',
            field=models.IntegerField(blank=True, null=True, verbose_name='Euro price'),
        ),
        migrations.AddField(
            model_name='servicesfull',
            name='price_lir',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lira price'),
        ),
        migrations.AddField(
            model_name='workfull',
            name='price_dol',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dollar price'),
        ),
        migrations.AddField(
            model_name='workfull',
            name='price_eur',
            field=models.IntegerField(blank=True, null=True, verbose_name='Euro price'),
        ),
        migrations.AddField(
            model_name='workfull',
            name='price_lir',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lira price'),
        ),
    ]
