# Generated by Django 4.0 on 2022-12-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0006_workfull_title_en_workfull_title_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workfull',
            name='for_work_type_ru',
            field=models.CharField(choices=[('для работы', 'для работы'), ('для работника', 'для работника')], max_length=255),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='for_work_type_tr',
            field=models.CharField(choices=[('iş için', 'iş için'), ('Bir çalışan için', 'Bir çalışan için')], max_length=255),
        ),
    ]
