# Generated by Django 4.1.4 on 2023-03-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0007_avtofull_price_dol_avtofull_price_eur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avtofull',
            name='price_dol',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Dollar price'),
        ),
        migrations.AlterField(
            model_name='avtofull',
            name='price_eur',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Euro price'),
        ),
        migrations.AlterField(
            model_name='avtofull',
            name='price_lir',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Lira price'),
        ),
        migrations.AlterField(
            model_name='childrenfull',
            name='price_dol',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Dollar price'),
        ),
        migrations.AlterField(
            model_name='childrenfull',
            name='price_eur',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Euro price'),
        ),
        migrations.AlterField(
            model_name='childrenfull',
            name='price_lir',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Lira price'),
        ),
        migrations.AlterField(
            model_name='electronicsfull',
            name='price_dol',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Dollar price'),
        ),
        migrations.AlterField(
            model_name='electronicsfull',
            name='price_eur',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Euro price'),
        ),
        migrations.AlterField(
            model_name='electronicsfull',
            name='price_lir',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Lira price'),
        ),
        migrations.AlterField(
            model_name='fashionfull',
            name='price_dol',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Dollar price'),
        ),
        migrations.AlterField(
            model_name='fashionfull',
            name='price_eur',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Euro price'),
        ),
        migrations.AlterField(
            model_name='fashionfull',
            name='price_lir',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Lira price'),
        ),
        migrations.AlterField(
            model_name='freefull',
            name='price_dol',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Dollar price'),
        ),
        migrations.AlterField(
            model_name='freefull',
            name='price_eur',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Euro price'),
        ),
        migrations.AlterField(
            model_name='freefull',
            name='price_lir',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Lira price'),
        ),
        migrations.AlterField(
            model_name='housegardenfull',
            name='price_dol',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Dollar price'),
        ),
        migrations.AlterField(
            model_name='housegardenfull',
            name='price_eur',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Euro price'),
        ),
        migrations.AlterField(
            model_name='housegardenfull',
            name='price_lir',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Lira price'),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='price_dol',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Dollar price'),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='price_eur',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Euro price'),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='price_lir',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Lira price'),
        ),
        migrations.AlterField(
            model_name='servicesfull',
            name='price_dol',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Dollar price'),
        ),
        migrations.AlterField(
            model_name='servicesfull',
            name='price_eur',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Euro price'),
        ),
        migrations.AlterField(
            model_name='servicesfull',
            name='price_lir',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Lira price'),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='price_dol',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Dollar price'),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='price_eur',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Euro price'),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='price_lir',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Lira price'),
        ),
    ]
