# Generated by Django 4.0 on 2022-12-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0007_alter_workfull_for_work_type_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workfull',
            name='salary',
        ),
        migrations.AlterField(
            model_name='workfull',
            name='employment_ru',
            field=models.CharField(choices=[('На постоянной основе', 'На постоянной основе'), ('Частичный', 'Частичный'), ('Удаленный', 'Удаленный')], max_length=255),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='employment_tr',
            field=models.CharField(choices=[('Tam zamanlı', 'Tam zamanlı'), ('Kısmi', 'Kısmi'), ('Uzak', 'Uzak')], max_length=255),
        ),
    ]
