# Generated by Django 4.0 on 2022-12-11 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0008_remove_workfull_salary_alter_workfull_employment_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avtofull',
            old_name='sub_apartment_en',
            new_name='sub_category_en',
        ),
        migrations.RenameField(
            model_name='avtofull',
            old_name='sub_apartment_ru',
            new_name='sub_category_ru',
        ),
        migrations.RenameField(
            model_name='avtofull',
            old_name='sub_apartment_tr',
            new_name='sub_category_tr',
        ),
        migrations.RenameField(
            model_name='realtyfull',
            old_name='sub_apartment_en',
            new_name='sub_category_en',
        ),
        migrations.RenameField(
            model_name='realtyfull',
            old_name='sub_apartment_ru',
            new_name='sub_category_ru',
        ),
        migrations.RenameField(
            model_name='realtyfull',
            old_name='sub_apartment_tr',
            new_name='sub_category_tr',
        ),
        migrations.RenameField(
            model_name='workfull',
            old_name='sub_apartment_en',
            new_name='sub_category_en',
        ),
        migrations.RenameField(
            model_name='workfull',
            old_name='sub_apartment_ru',
            new_name='sub_category_ru',
        ),
        migrations.RenameField(
            model_name='workfull',
            old_name='sub_apartment_tr',
            new_name='sub_category_tr',
        ),
    ]
