# Generated by Django 4.1.4 on 2023-03-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0009_alter_avtofull_price_dol_alter_avtofull_price_eur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtyfull',
            name='all_old_new_ru',
            field=models.CharField(blank=True, choices=[('Все', 'Все'), ('Вторичное', 'Вторичное'), ('Новое', 'Новое')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='number_rooms_en',
            field=models.CharField(blank=True, choices=[('Studio', 'Studio'), ('1+1', '1+1'), ('2+1', '2+1'), ('2+2', '2+2'), ('3+1', '3+1'), ('4+1 and more', '4+1 and more')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='number_rooms_ru',
            field=models.CharField(blank=True, choices=[('Студия', 'Студия'), ('1+1', '1+1'), ('2+1', '2+1'), ('2+2', '2+2'), ('3+1', '3+1'), ('4+1 и более', '4+1 и более')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='number_rooms_tr',
            field=models.CharField(blank=True, choices=[('Stüdyo', 'Stüdyo'), ('1+1', '1+1'), ('2+1', '2+1'), ('2+2', '2+2'), ('3+1', '3+1'), ('4+1 ve üzeri', '4+1 ve üzeri')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='sub_category_ru',
            field=models.CharField(blank=True, choices=[('Апартаменты', 'Апартаменты'), ('Дом', 'Дом'), ('Земля', 'Земля'), ('Другое', 'Другое')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='employment_ru',
            field=models.CharField(blank=True, choices=[('На постоянной основе', 'На постоянной основе'), ('Частичный', 'Частичный'), ('Дистанционно', 'Дистанционно')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='sub_category_en',
            field=models.CharField(blank=True, choices=[('Retail | Sales | Procurement', 'Retail | Sales | Procurement'), ('Logistics | Warehouse | Delivery', 'Logistics | Warehouse | Delivery'), ('Construction | finishing works', 'Construction | finishing works'), ('Administrative staff | HR | Secretariat', 'Administrative staff | HR | Secretariat'), ('Security | security', 'Security | security'), ('Cleaning | Home staff', 'Cleaning | Home staff'), ('Beauty | Fitness | Sports', 'Beauty | Fitness | Sports'), ('Education | translation', 'Education | translation'), ('Culture | Arts | Entertainment', 'Culture | Arts | Entertainment'), ('Medicine | Pharmacy', 'Medicine | Pharmacy'), ('IT | computers', 'IT | computers'), ('Banking | Finance | Insurance | Jurisprudence', 'Banking | Finance | Insurance | Jurisprudence'), ('Real estate', 'Real estate'), ('Advertising | Design | PR', 'Advertising | Design | PR'), ('Production | Working specialties', 'Production | Working specialties'), ('Work abroad', 'Work abroad'), ('Accounting', 'Accounting'), ('Hotel and restaurant business | Tourism', 'Hotel and restaurant business | Tourism'), ('Service stations | Car washes', 'Service stations | Car washes'), ('Part-time employment', 'Part-time employment'), ('Other occupations', 'Other occupations')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='sub_category_ru',
            field=models.CharField(blank=True, choices=[('Розничная торговля | Продажи | Приобретение', 'Розничная торговля | Продажи | Приобретение'), ('Логистика | Склад | Доставка', 'Логистика | Склад | Доставка'), ('Строительство | отделочные работы', 'Строительство | отделочные работы'), ('Административный персонал | HR | Секретариат', 'Административный персонал | HR | Секретариат'), ('Безопасность | безопасность', 'Безопасность | безопасность'), ('Уборка | Домашний персонал', 'Уборка | Домашний персонал'), ('Красота | Фитнес | Спорт', 'Красота | Фитнес | Спорт'), ('Образование | перевод', 'Образование | перевод'), ('Культура | Искусство | Развлечения', 'Культура | Искусство | Развлечения'), ('Медицина | Аптека', 'Медицина | Аптека'), ('IT | компьютеры', 'IT | компьютеры'), ('Банковское дело | Финансы | Страхование | Юриспруденция', 'Банковское дело | Финансы | Страхование | Юриспруденция'), ('Недвижимость', 'Недвижимость'), ('Реклама | Дизайн | Пиар', 'Реклама | Дизайн | Пиар'), ('Производство | Рабочие специальности', 'Производство | Рабочие специальности'), ('Работа за границей', 'Работа за границей'), ('Бухгалтерский учет', 'Бухгалтерский учет'), ('Отель и ресторанный бизнес | Туризм', 'Отель и ресторанный бизнес | Туризм'), ('Справочные станции | Автомобильные стирки', 'Справочные станции | Автомобильные стирки'), ('Неполная занятость', 'Неполная занятость'), ('Другие профессии', 'Другие профессии')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='sub_category_tr',
            field=models.CharField(blank=True, choices=[('Perakende | Satış | Tedarik', 'Perakende | Satış | Tedarik'), ('Lojistik | Depo | Teslimat', 'Lojistik | Depo | Teslimat'), ('İnşaat | İşleri bitirmek', 'İnşaat | İşleri bitirmek'), ('İdari Personel | HR | Sekreterlik', 'İdari Personel | HR | Sekreterlik'), ('Güvenlik | güvenlik', 'Güvenlik | güvenlik'), ('Temizlik | Ev personeli', 'Temizlik | Ev personeli'), ('Güzellik | Fitness | Spor Dalları', 'Güzellik | Fitness | Spor Dalları'), ('Eğitim | tercüme', 'Eğitim | tercüme'), ('Kültür | Sanat | Eğlence', 'Kültür | Sanat | Eğlence'), ('Tıp | Eczane', 'Tıp | Eczane'), ('IT | bilgisayar', 'IT | bilgisayar'), ('Bankacılık | Finans | Sigorta | İçtihat', 'Bankacılık | Finans | Sigorta | İçtihat'), ('Emlak', 'Emlak'), ('Reklam | Tasarım | PR', 'Reklam | Tasarım | PR'), ('Üretim | Çalışma Uzmanlıkları', 'Üretim | Çalışma Uzmanlıkları'), ('Yurt dışında çalışmak', 'Yurt dışında çalışmak'), ('Muhasebe', 'Muhasebe'), ('Otel ve Restoran İşletme | Turizm', 'Otel ve Restoran İşletme | Turizm'), ('Servis İstasyonları | Araba Yıkamaları', 'Servis İstasyonları | Araba Yıkamaları'), ('Yarı-zamanlı istihdam', 'Yarı-zamanlı istihdam'), ('Diğer Meslekler', 'Diğer Meslekler')], max_length=255, null=True),
        ),
    ]
