# Generated by Django 4.1.4 on 2023-03-27 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Pathname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathname', models.CharField(max_length=255)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seo.categorykey')),
            ],
        ),
        migrations.CreateModel(
            name='MetaTeg',
            fields=[
                ('pathname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='seo.pathname')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSchem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('pathname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seo.pathname')),
            ],
            options={
                'verbose_name': 'FAQ разметка',
            },
        ),
        migrations.CreateModel(
            name='MetaDescription',
            fields=[
                ('metateg_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='seo.metateg')),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Мета теги type=description',
            },
            bases=('seo.metateg',),
        ),
        migrations.CreateModel(
            name='MetaKeywords',
            fields=[
                ('metateg_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='seo.metateg')),
                ('keywords', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Мета теги type=keywords',
            },
            bases=('seo.metateg',),
        ),
    ]
