# Generated by Django 4.1.4 on 2023-03-18 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaCategoryKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MetaTeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathname', models.CharField(max_length=255)),
                ('category_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seo.metacategorykey')),
            ],
        ),
        migrations.CreateModel(
            name='MetaDescription',
            fields=[
                ('metateg_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='seo.metateg')),
                ('text', models.CharField(max_length=255)),
            ],
            bases=('seo.metateg',),
        ),
        migrations.CreateModel(
            name='MetaKeywords',
            fields=[
                ('metateg_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='seo.metateg')),
                ('keywords', models.CharField(max_length=255)),
            ],
            bases=('seo.metateg',),
        ),
    ]
