# Generated by Django 4.1.4 on 2023-03-18 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_categorykey_alter_metadescription_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorykey',
            options={'verbose_name': 'Категории '},
        ),
        migrations.AlterModelOptions(
            name='metadescription',
            options={'verbose_name': 'Мета теги type=description '},
        ),
        migrations.AlterModelOptions(
            name='metakeywords',
            options={'verbose_name': 'Мета теги type=keywords '},
        ),
        migrations.RemoveField(
            model_name='metateg',
            name='category_key',
        ),
    ]
