# Generated by Django 4.1.4 on 2023-03-18 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_alter_categorykey_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSchem',
            fields=[
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('pathname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='seo.pathname')),
            ],
            options={
                'verbose_name': 'FAQ разметка',
            },
        ),
        migrations.AlterModelOptions(
            name='categorykey',
            options={'verbose_name': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='metadescription',
            options={'verbose_name': 'Мета теги type=description'},
        ),
        migrations.AlterModelOptions(
            name='metakeywords',
            options={'verbose_name': 'Мета теги type=keywords'},
        ),
    ]
