# Generated by Django 4.1.4 on 2023-03-18 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0004_questionschem_alter_categorykey_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionschem',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionschem',
            name='pathname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seo.pathname'),
        ),
    ]
