# Generated by Django 4.1.4 on 2023-03-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_connectedusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='advert_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='category_key',
            field=models.CharField(choices=[('realty', 'realty'), ('work', 'work'), ('services', 'services'), ('free', 'free'), ('avto', 'avto'), ('house_garden', 'house_garden'), ('electronics', 'electronics'), ('children', 'children'), ('fashion', 'fashion')], default='avto', max_length=100),
            preserve_default=False,
        ),
    ]
