# Generated by Django 4.0.6 on 2023-03-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
