# Generated by Django 4.1.4 on 2023-03-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_group_advert_id_group_category_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
    ]
