version: '3'
services:

  nginx:
    build: ./nginx
    container_name: nginx
    links:
      - frontend
      - backend
    depends_on:
      - frontend
      - backend
    volumes:
      - static_volume:/app/backend/staticfiles
      - media_volume:/app/backend/media
    ports:
      - "80:80"
      - "443:443"

#  postgresql:
#    image: postgres:12.0-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=MTAIDnLu
#      - POSTGRES_DB=postgres
#    ports:
#      - "5432:5432"

  backend:
    build: ./backend
    container_name: api
    command: >
      sh -c " python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py initadmin &&
              python manage.py collectstatic --noinput &&
              gunicorn settings.wsgi:application --bind 0.0.0.0:8000 --log-level debug --workers=15 --worker-class=gevent --worker-connections=500"
    volumes:
      - static_volume:/app/backend/staticfiles
      - media_volume:/app/backend/media
#    depends_on:
#      - postgresql
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: frontend
#    depends_on:
#      - postgresql
    ports:
      - "3000:3000"

volumes:
  media_volume:
  static_volume: