version: '3.9'
services:
  nginx:
    build: ./nginx
    container_name: nginx
    links:
      - backend
    depends_on:
      - backend
    volumes:
      - static_volume:/app/backend/staticfiles
      - media_volume:/app/backend/media
    ports:
      - "80:80"
      - "443:443"
  backend:
    container_name: api
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/backend/staticfiles
      - media_volume:/app/backend/media
#  postgresql:
#    image: postgres:12.0-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=MTAIDnLu
#      - POSTGRES_DB=postgres
#    ports:
#      - "5432:5432"
volumes:
  media_volume:
  static_volume: