# Generated by Django 4.0 on 2022-11-10 19:15

from django.db import migrations, models
import django.db.models.deletion
import sections.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Realty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1024, verbose_name='The address is')),
                ('apartment_number', models.CharField(max_length=255, verbose_name='Apartment number')),
                ('place_ad', models.CharField(choices=[('Owner', 'Owner'), ('Mediator', 'Mediator')], max_length=255, verbose_name='Places an ad')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('com_method', models.CharField(choices=[('By phone and text message', 'By phone and text message'), ('By phone', 'By phone')], max_length=255, verbose_name='Communication method')),
                ('onl_screening', models.CharField(choices=[('Conducting', 'Conducting'), ('I dont want to.', 'I dont want to.')], max_length=255, verbose_name='Online-Screening')),
                ('int_floor', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99)], max_length=3, verbose_name='Floor of the house')),
                ('numbers_rooms', models.CharField(choices=[('Studio', 'Studio'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), ('10 rooms and more', '10 rooms and more'), ('Free layout', 'Free layout')], max_length=255, verbose_name='Number of rooms')),
                ('balcony', models.BooleanField(verbose_name='Balcony')),
                ('loggia', models.BooleanField(verbose_name='Loggia')),
                ('wardrobe', models.BooleanField(verbose_name='The Wardrobe')),
                ('panoramic_windows', models.BooleanField(verbose_name='Panoramic windows')),
                ('total_area', models.IntegerField(verbose_name='Total Area')),
                ('kitchen_area', models.IntegerField(verbose_name='Kitchen Area')),
                ('live_area', models.IntegerField(verbose_name='Live Area')),
                ('ceiling_height', models.IntegerField(verbose_name='Ceiling height')),
                ('combined', models.BooleanField(verbose_name='Combined')),
                ('divided', models.BooleanField(verbose_name='Divided')),
                ('windows', models.BooleanField(verbose_name='Windows')),
                ('courtyard', models.BooleanField(verbose_name='In the courtyard')),
                ('outside', models.BooleanField(verbose_name='On the street')),
                ('sunny_side', models.BooleanField(verbose_name='Sunny side')),
                ('repair', models.CharField(choices=[('Required', 'Required'), ('Cosmic', 'Cosmic'), ('Euro', 'Euro'), ('Design', 'Design')], max_length=255, verbose_name='Repair')),
                ('underfloor_heating', models.BooleanField(verbose_name='Underfloor heating')),
                ('furniture', models.BooleanField(verbose_name='Furniture')),
                ('kitchen', models.BooleanField(verbose_name='Kitchen')),
                ('storing_clothes', models.BooleanField(verbose_name='Storing clothes')),
                ('sleeping_places', models.BooleanField(verbose_name='Sleeping places')),
                ('air_conditioner', models.BooleanField(verbose_name='Air conditioner')),
                ('refrigerator', models.BooleanField(verbose_name='Refrigerator')),
                ('washing_machine', models.BooleanField(verbose_name='Washing machine')),
                ('dishwasher', models.BooleanField(verbose_name='Dishwasher')),
                ('water_heater', models.BooleanField(verbose_name='Water heater')),
                ('type_house', models.CharField(choices=[('Brick', 'Brick'), ('Panel', 'Panel'), ('Block', 'Block'), ('Monolithic', 'Monolithic'), ('Monolithic Brick', 'Monolithic Brick'), ('Wooden', 'Wooden')], max_length=255, verbose_name='Type House')),
                ('year_construction', models.IntegerField(verbose_name='Year of construction')),
                ('concierge', models.BooleanField(verbose_name='Concierge')),
                ('garbage_chute', models.BooleanField(verbose_name='Garbage chute')),
                ('gas', models.BooleanField(verbose_name='Gas')),
                ('floors_house', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99)], max_length=3, verbose_name='Floors in the house')),
                ('planned_demolition', models.BooleanField(verbose_name='Planned demolition')),
                ('elevator_passenger', models.CharField(choices=[('No', 'No'), (1, 1), (2, 2), (3, 3), (4, 4)], max_length=255, verbose_name='Elevator Passenger')),
                ('elevator_cargo', models.CharField(choices=[('No', 'No'), (1, 1), (2, 2), (3, 3), (4, 4)], max_length=255, verbose_name='Elevator Cargo')),
                ('closed_area', models.BooleanField(verbose_name='Closed area')),
                ('playground', models.BooleanField(verbose_name='Playground')),
                ('sports_field', models.BooleanField(verbose_name='Sports field')),
                ('underground', models.BooleanField(verbose_name='Underground')),
                ('ground_multilevel', models.BooleanField(verbose_name='Ground multilevel')),
                ('open_yard', models.BooleanField(verbose_name='Open in the yard')),
                ('behind_barrier_yard', models.BooleanField(verbose_name='Behind the barrier in the yard')),
                ('upload', models.FileField(blank=True, upload_to='')),
                ('url_video', models.URLField()),
                ('description', models.TextField()),
                ('selling_method', models.CharField(choices=[('Free', 'Free'), ('Alternative', 'Alternative')], max_length=255)),
                ('can_be_mortgaged', models.BooleanField(verbose_name='Can be mortgaged')),
                ('sale_share', models.BooleanField(verbose_name='Sale of a share')),
                ('auction', models.BooleanField(verbose_name='Auction')),
                ('starting_price', models.IntegerField(verbose_name='Starting price')),
            ],
        ),
        migrations.CreateModel(
            name='RealtyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realty_category', models.CharField(choices=[('Apartments', 'Apartments'), ('Rooms', 'Rooms'), ('Houses, Dachas, Cottages', 'Houses, Dachas, Cottages'), ('Land', 'Land'), ('Garages and Parking spaces', 'Garages and Parking spaces'), ('Commercial Real Estate', 'Commercial Real Estate'), ('Real Estate Abroad', 'Real Estate Abroad')], max_length=255)),
                ('realty_category_type', models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent'), ('Buying', 'Buying'), ('Retrieved', 'Retrieved')], max_length=255)),
                ('realty_category_type_use', models.CharField(blank=True, choices=[('Secondary', 'Secondary'), ('New Building', 'New Building'), ('For a long time', 'For a long time'), ('Daily', 'Daily')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RealtyUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploads', models.FileField(upload_to=sections.models.user_directory_path)),
                ('realtys', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sections.realty')),
            ],
        ),
        migrations.AddField(
            model_name='realty',
            name='realty_category_use',
            field=models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.PROTECT, to='sections.realtycategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='realty',
            name='user_realty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser', verbose_name='User'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sections.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser', verbose_name='User')),
            ],
        ),
    ]
