# Generated by Django 4.0 on 2022-12-05 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sections', '0003_realtyfull_category_delete_basecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtyfull',
            name='category',
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser', verbose_name='User'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Product name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=1024, verbose_name='The address is')),
                ('price', models.IntegerField(verbose_name='Starting price')),
                ('category', models.CharField(blank=True, choices=[('Real estate', 'Real estate'), ('Auto', 'Auto'), ('Job', 'Job'), ('Services', 'Services'), ('For kids', 'For kids'), ('Electronics', 'Electronics'), ('House and garden', 'House and garden'), ('Fashion and style', 'Fashion and style')], default=None, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser', verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
