# Generated by Django 4.0 on 2022-12-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_remove_realtyfull_category_alter_realtyfull_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='upload',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
