# Generated by Django 4.0 on 2022-12-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0006_realtyfull_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtyfull',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='realtyfull',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Product name'),
        ),
    ]
