# Generated by Django 4.0 on 2022-12-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0007_realtyfull_title_en_realtyfull_title_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtyfull',
            name='title_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Product name'),
        ),
    ]
