# Generated by Django 4.0 on 2022-12-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0009_realtyfull_category_en_realtyfull_category_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtyfull',
            name='all_old_new_en',
            field=models.CharField(choices=[('All', 'All'), ('Old', 'Old'), ('New', 'New')], max_length=255, null=True, verbose_name='ALL OLD NEW'),
        ),
        migrations.AddField(
            model_name='realtyfull',
            name='all_old_new_ru',
            field=models.CharField(choices=[('All', 'All'), ('Old', 'Old'), ('New', 'New')], max_length=255, null=True, verbose_name='ALL OLD NEW'),
        ),
        migrations.AddField(
            model_name='realtyfull',
            name='all_old_new_tr',
            field=models.CharField(choices=[('All', 'All'), ('Old', 'Old'), ('New', 'New')], max_length=255, null=True, verbose_name='ALL OLD NEW'),
        ),
        migrations.AddField(
            model_name='realtyfull',
            name='number_rooms_en',
            field=models.CharField(choices=[('Studio', 'Studio'), ('1+1', '1+1'), ('2+1', '2+1'), ('3+1', '3+1'), ('4+1 and more', '4+1 and more')], max_length=255, null=True, verbose_name='Number Rooms'),
        ),
        migrations.AddField(
            model_name='realtyfull',
            name='number_rooms_ru',
            field=models.CharField(choices=[('Studio', 'Studio'), ('1+1', '1+1'), ('2+1', '2+1'), ('3+1', '3+1'), ('4+1 and more', '4+1 and more')], max_length=255, null=True, verbose_name='Number Rooms'),
        ),
        migrations.AddField(
            model_name='realtyfull',
            name='number_rooms_tr',
            field=models.CharField(choices=[('Studio', 'Studio'), ('1+1', '1+1'), ('2+1', '2+1'), ('3+1', '3+1'), ('4+1 and more', '4+1 and more')], max_length=255, null=True, verbose_name='Number Rooms'),
        ),
        migrations.AddField(
            model_name='realtyfull',
            name='sell_type_en',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Buy', 'Buy')], max_length=255, null=True, verbose_name='Category type use'),
        ),
        migrations.AddField(
            model_name='realtyfull',
            name='sell_type_ru',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Buy', 'Buy')], max_length=255, null=True, verbose_name='Category type use'),
        ),
        migrations.AddField(
            model_name='realtyfull',
            name='sell_type_tr',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Buy', 'Buy')], max_length=255, null=True, verbose_name='Category type use'),
        ),
        migrations.AddField(
            model_name='realtyfull',
            name='sub_apartment_en',
            field=models.CharField(choices=[('Apartments', 'Apartments'), ('House', 'House'), ('Land', 'Land'), ('Other', 'Other')], max_length=255, null=True, verbose_name='Sub Apartment'),
        ),
        migrations.AddField(
            model_name='realtyfull',
            name='sub_apartment_ru',
            field=models.CharField(choices=[('Apartments', 'Apartments'), ('House', 'House'), ('Land', 'Land'), ('Other', 'Other')], max_length=255, null=True, verbose_name='Sub Apartment'),
        ),
        migrations.AddField(
            model_name='realtyfull',
            name='sub_apartment_tr',
            field=models.CharField(choices=[('Apartments', 'Apartments'), ('House', 'House'), ('Land', 'Land'), ('Other', 'Other')], max_length=255, null=True, verbose_name='Sub Apartment'),
        ),
    ]
