# Generated by Django 4.0 on 2022-12-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0010_realtyfull_all_old_new_en_realtyfull_all_old_new_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtyfull',
            name='category',
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='category_ru',
            field=models.CharField(blank=True, choices=[('Недвижимость', 'Недвижимость'), ('Авто', 'Авто'), ('Работа', 'Работа'), ('Услуги', 'Услуги'), ('Для детей', 'Для детей'), ('Электроника', 'Электроника'), ('Дом и сад', 'Дом и сад'), ('Мода и стиль', 'Мода и стиль')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Otomatik', 'Otomatik'), ('İş', 'iş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True),
        ),
    ]
