# Generated by Django 4.0 on 2022-12-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0011_remove_realtyfull_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtyfull',
            name='sub_apartment',
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='category_ru',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='sub_apartment_en',
            field=models.CharField(choices=[('Apartments', 'Apartments'), ('House', 'House'), ('Land', 'Land'), ('Other', 'Other')], default=1, max_length=255, verbose_name='Sub Apartment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='sub_apartment_ru',
            field=models.CharField(choices=[('Квартиры', 'Квартиры'), ('Дом', 'Дом'), ('Земельные участки', 'Земельные участки'), ('Другой', 'Другой')], default=1, max_length=255, verbose_name='Sub Apartment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='sub_apartment_tr',
            field=models.CharField(choices=[('Daireler', 'Daireler'), ('Ev', 'Ev'), ('Kara', 'Kara'), ('Başka', 'Başka')], default=1, max_length=255, verbose_name='Sub Apartment'),
            preserve_default=False,
        ),
    ]
