# Generated by Django 4.0 on 2022-12-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0012_remove_realtyfull_sub_apartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtyfull',
            name='category_ru',
            field=models.CharField(blank=True, choices=[('Недвижимость', 'Недвижимость'), ('Авто', 'Авто'), ('Работа', 'Работа'), ('Услуги', 'Услуги'), ('Для детей', 'Для детей'), ('Электроника', 'Электроника'), ('Дом и сад', 'Дом и сад'), ('Мода и стиль', 'Мода и стиль')], default=None, max_length=255, null=True),
        ),
    ]
