# Generated by Django 4.0 on 2022-12-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0013_alter_realtyfull_category_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtyfull',
            name='all_old_new',
        ),
        migrations.RemoveField(
            model_name='realtyfull',
            name='number_rooms',
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='all_old_new_en',
            field=models.CharField(choices=[('All', 'All'), ('Old', 'Old'), ('New', 'New')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='all_old_new_ru',
            field=models.CharField(choices=[('Все', 'Все'), ('Старый', 'Старый'), ('Новый', 'Новый')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='all_old_new_tr',
            field=models.CharField(choices=[('Herşey', 'Herşey'), ('Eskimiş', 'Eskimiş'), ('Yeni', 'Yeni')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='number_rooms_en',
            field=models.CharField(choices=[('Studio', 'Studio'), ('1+1', '1+1'), ('2+1', '2+1'), ('3+1', '3+1'), ('4+1 and more', '4+1 and more')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='number_rooms_ru',
            field=models.CharField(choices=[('Студия', 'Студия'), ('1+1', '1+1'), ('2+1', '2+1'), ('3+1', '3+1'), ('4+1 и больше', '4+1 и больше')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='number_rooms_tr',
            field=models.CharField(choices=[('Stüdyo', 'Stüdyo'), ('1+1', '1+1'), ('2+1', '2+1'), ('3+1', '3+1'), ('4+1 ve daha fazlası', '4+1 ve daha fazlası')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
