# Generated by Django 4.0 on 2022-12-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0014_remove_realtyfull_all_old_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtyfull',
            name='sell_type',
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='sell_type_en',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Buy', 'Buy')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='sell_type_ru',
            field=models.CharField(choices=[('Арендовать', 'Арендовать'), ('Купить', 'Купить')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='sell_type_tr',
            field=models.CharField(choices=[('Kiraya vermek', 'Kiraya vermek'), ('Satın almak', 'Satın almak')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
