# Generated by Django 4.0 on 2022-12-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0015_remove_realtyfull_sell_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtyfull',
            name='en_ru_tr',
            field=models.CharField(choices=[('English', 'English'), ('Русский', 'Русский'), ('Türk', 'Türk')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
