# Generated by Django 4.0 on 2022-12-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0016_realtyfull_en_ru_tr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtyfull',
            name='en_ru_tr',
        ),
    ]
