# Generated by Django 4.0 on 2022-12-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0017_remove_realtyfull_en_ru_tr'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtyfull',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('tr', 'Türk')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
