# Generated by Django 4.0 on 2022-12-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0018_realtyfull_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtyfull',
            name='language',
        ),
        migrations.AddField(
            model_name='realtyfull',
            name='en',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtyfull',
            name='ru',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtyfull',
            name='tr',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
