# Generated by Django 4.0 on 2022-12-06 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0019_remove_realtyfull_language_realtyfull_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtyfull',
            name='en',
        ),
        migrations.RemoveField(
            model_name='realtyfull',
            name='ru',
        ),
        migrations.RemoveField(
            model_name='realtyfull',
            name='tr',
        ),
    ]
