# Generated by Django 4.0 on 2022-12-06 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0020_remove_realtyfull_en_remove_realtyfull_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtyfull',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
