# Generated by Django 4.1.4 on 2023-01-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deals',
            field=models.IntegerField(default=0),
        ),
    ]
