# Generated by Django 4.0 on 2022-12-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='addres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
