# Generated by Django 4.0 on 2022-12-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='addres',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
